version: '3'
services:
  dnscrypt-proxy:
    build: .
    image: goonnowgit/dnscrypt-proxy:2.1.1
    command: -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml
    cap_drop:
      - ALL
    ports:
    - "5300:5300"
    - "5300:5300/udp"
    restart: unless-stopped
    volumes:
      - ./confs:/etc/dnscrypt-proxy
      - ./certs:/etc/dnscrypt-proxy/certs/
      - ./acls:/etc/dnscrypt-proxy/acls
      - ./logs:/var/log/dnscrypt-proxy
      - ./run:/var/run
